## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
#baseURL = ""
#publishDir = "public"

# Remote
baseURL = "https://surinamerunningcollective.onrender.com"
publishDir = "public"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  favicon = false

[menu]
  [[menu.main]]
    name = "Weekly Runs"
    url = "#weekly"
    weight = 10

  [[menu.main]]
    name = "Events"
    url = "#events"
    weight = 20

  [[menu.main]]
    name = "Routes"
    url = "#routes"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 50
    

[Params.social]

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  own_css = ["css/own.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]