---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/site.yml
  label: site socials
- type: document
  path: data/banner.yml
  label: welcome banner
- type: document
  path: data/weekly.yml
  label: weekly runs
- type: document
  path: data/upcoming.yml
  label: upcoming runs
- type: document
  path: data/routes.yml
  label: routes
- type: document
  path: data/about.yml
  label: about
  match: "**/*"
upload_dir: static
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
